### ISSUE TITLE
website package search very buggy

### ISSUE THREAD

**Issue by whitis** [tim-lebedkov/npackd-gae-web#1]
There are 1161 packages.  You can only browse the first 1019 of them quasi-alphabetically before the server blows up.    And at that point it is WAY TO LATE to browse by category.

https://npackd.appspot.com/p?start=1020&q=
"Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds."
It won't succeed later.  if start is greater than 1000 it fails consistently.   1000 succeeds, 1001 fails.

Also, occasionally the packages are not in alphabetical order and related packages are not next to each other (32 vs 64 bit),

Search inflicts categories on you without your consent and refuses to remove them.   This frequently results in searches being unsuccesful or returning fewer results than they should.
   Search for "synergy".   2 matches.  "tools" category imposed.    Now search for "text editor": 0 matches, whether or not you click on "tools" to remove it.  (Chrome Version 60.0.3112.101 (Official Build) (64-bit) on Ubuntu 14.04).

Search is poor, only whole words match, with no synonyms.
    "dvd burn": 0 matchers
    "dvd burner" 0 matches
    "dvd burning": 6 matches
   "dvd": 12 matches, ok, this should be broader
 When combined with the previous bug and the dubious choice of keywords, things get very confusing.

There is no way to increase the number of results per page.

**Comment by tim-lebedkov** [comment]
word stemming is now also implemented
